### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by FisH-2022** [ctripcorp/tripdocs#1]
![image](https://user-images.githubusercontent.com/99541071/212101060-a127b740-02f9-43dc-ac3d-3847d93e613d.png)
## **文本类型这里，选中了一种类型以后，字下面一点点会被挡掉**

![image](https://user-images.githubusercontent.com/99541071/212101657-e074088d-d1c9-4b4d-bd7f-effb94a6f2bc.png)

**Comment by PangYiMing** [comment]
感谢反馈，我们会在接下来的迭代中修复它

**Comment by PangYiMing** [comment]
下一步版本同步会带上
