### ISSUE TITLE
请问这个编辑器如何支持协同参与呢

### ISSUE THREAD

**Issue by l54808821** [ctripcorp/tripdocs#2]
请问这个编辑器如何支持协同参与呢

**Comment by PangYiMing** [comment]
使用[slate-collaborative](https://github.com/cudr/slate-collaborative) 搭建服务器，修改项目中socketUrl字段为你的服务器地址即可

**Comment by uptonking** [comment]
@PangYiMing 协作不是用的slate-yjs吗，而[slate-collaborative](https://github.com/cudr/slate-collaborative)用的是automerge，readme里面是不是写错了
- 希望给一个本地运行协作的示例 :heart:

**Comment by cactuser-Lu** [comment]
> @PangYiMing 协作不是用的slate-yjs吗，而[slate-collaborative](https://github.com/cudr/slate-collaborative)用的是automerge，readme里面是不是写错了
> 
> * 希望给一个本地运行协作的示例 ❤️

参考这个https://docs.yjs.dev/ecosystem/connection-provider/y-websocket，直接运行PORT=1234 YPERSISTENCE=./dbDir node ./node_modules/y-websocket/bin/server.js就可以

**Comment by cactuser-Lu** [comment]
> @PangYiMing 协作不是用的slate-yjs吗，而[slate-collaborative](https://github.com/cudr/slate-collaborative)用的是automerge，readme里面是不是写错了
> 
> * 希望给一个本地运行协作的示例 ❤️

参考这个[https://docs.yjs.dev/ecosystem/connection-provider/y-websocket]，直接运行PORT=1234] YPERSISTENCE=./dbDir node ./node_modules/y-websocket/bin/server.js就可以
